In [172]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import string
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anvitmangal/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [39]:
data = pd.read_csv('output_meta_yelpResData_NRYRcleaned.csv', names = ['date', 'review_id', 'reviewer_id', 'business_id', 'label', 'usefull', 'funny', 'cool', 'Stars'])

In [40]:
len(data.index)

61541

In [41]:
text_review = pd.read_csv('output_review_yelpResData_NRYRcleaned.csv', names = ['review'])

In [42]:
len(text_review.index)

61541

In [43]:
data['date'] =  pd.to_datetime(data['date'])

In [47]:
full_review = pd.concat([data, text_review], axis=1)

In [48]:
full_review

,date,review_id,reviewer_id,business_id,label,usefull,funny,cool,Stars,review
0,2012-09-22,GtwU21YOQn-wf4vWRUIx6w,bNYesZ944s6IJVowOnB0iA,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,"Unlike Next, which we'd eaten at the previous ..."
1,2012-09-22,0LpVTc3,TRKxLC3y-ZvP45e5iilMtw,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,Probably one of the best meals I've had ever. ...
2,2012-09-19,tljtLzf68Fkwf,0EMm8umAqXZzyhxNpL4M9g,pbEiXam9YJL3neCYHGwLUA,N,0,0,2,3,Service was impeccable. Experience and present...
3,2012-09-06,iSN,DlwexC7z88ymAzu45skODw,pbEiXam9YJL3neCYHGwLUA,N,3,0,8,3,"The problem with places like this, given the e..."
4,2012-09-09,Jmwrh7,kW2dk1CWihmh3g7k9N2G8A,pbEiXam9YJL3neCYHGwLUA,N,0,2,1,5,I have no idea how to write my review - dining...
5,2012-08-30,lKlceLWoePzeuvFD3sj4mw,HxXEcMDDTJFUqVfhPF9M8Q,pbEiXam9YJL3neCYHGwLUA,N,1,1,3,5,Despite the first-world tragedy I endured in a...
6,2012-09-08,PBS2uyee9V5IpFfTropxbw,OW2H-GkKnlVEBPuGHIaiFg,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,5,"Overall, was it worth the hype? Yes and more. ..."
7,2012-08-24,PkwbB,BSh3h1J4mdSmEsb8FFdf0Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,8,3,There are already TONS of professional & amate...
8,2012-08-22,MRdliMXsmP1ViLjA5oCO,F3mbveXX30Ou0gpDY6IrCQ,pbEiXam9YJL3neCYHGwLUA,N,3,7,3,5,Your life is a countdown ever since you're bor...
9,2012-08-23,z-j4X,NvSnBp4fTpNOfDwm2GWusA,pbEiXam9YJL3neCYHGwLUA,N,0,0,3,5,Lots of complaints about how difficult it is t...
10,2012-08-26,VXtDGw7E0guWdXLOtzKJ3w,dCbC5DeMbsRsP0bw7RRG0w,pbEiXam9YJL3neCYHGwLUA,N,0,0,4,3,1st I will say I'm not a foodie but I enjoy di...
11,2012-09-11,V0PU0ciEBeNiHHS1,-3Mzc2O6jmYLWQJcIJdvAA,pbEiXam9YJL3neCYHGwLUA,N,0,1,1,5,Today marks one year since my dinner at Alinea...
12,2012-08-16,revID_update_res1,Or40sZeUkVa2w1SCjhaUVg,pbEiXam9YJL3neCYHGwLUA,N,0,1,3,5,"In my four years as a member of Yelp!, I've wr..."
13,2012-08-04,9Q17H2GMBFeRMOS1Ni-I2Q,tToOHav143V1NXH0nf_YIA,pbEiXam9YJL3neCYHGwLUA,N,10,10,10,5,"I had wanted to visit Alinea since 2007, but w..."
14,2012-09-15,Hk9BR0a,EkItn2a_Fx1KE9Q5amo7JA,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,I dined at Alinea a few weeks ago with my son ...
15,2012-08-21,MgarFT5mQE6Gq1eNAfw4Fw,0SvPdzpIEHQFJOvnPt9zxQ,pbEiXam9YJL3neCYHGwLUA,N,1,1,0,5,"So, we were fortunate enough to score Sunday d..."
16,2012-08-06,8cP116ZiSEmSv8vYTI6RIA,hFaZatmXXpiEDyMFaLejmw,pbEiXam9YJL3neCYHGwLUA,N,2,3,1,5,All of these reviews likely tell you the vario...
17,2012-08-23,UgYDx0tIBklPYQM1VS-B,NAWMYBSkEPAEYp9YT7vM_Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,This is really the greatest restaurant I have ...
18,2012-08-13,6A7MFnTHM45U0pKl379KRw,_Es4as5v1edu5WxeMvWHEg,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,4,Maybe I should have read reviews of this place...
19,2012-08-08,If-jhodOvle7Qm6LBK-GTA,yGrCzVPdeHTiFl5KfUVZBA,pbEiXam9YJL3neCYHGwLUA,N,0,1,1,5,I have never worked this hard to get a reserva...
20,2012-09-08,Xz9kC-QlnKL1CO6hSihR0w,7MczEWaY3Ic6p4kBkKH0gw,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,5,"The best restaurant I have ever been to, hands..."
21,2012-08-30,JJB4ji7KzToqwdW3CRad,TYfZrIzz08VGmvvvGZhqyw,pbEiXam9YJL3neCYHGwLUA,N,0,0,5,5,"First, let me start by saying that it took me ..."
22,2012-08-16,aeEjv1lz5q0E0k6uf0gZ4w,gmluXHnW8aihzYow1zVoRQ,pbEiXam9YJL3neCYHGwLUA,N,0,0,3,2,Part of me wants to give this resto five stars...
23,2012-08-12,6--qR6eWCaLsVFsoZYELAA,9_Hqx7Bf5vwQsgP2g-WCCQ,pbEiXam9YJL3neCYHGwLUA,N,1,1,1,5,The day had finally come for our dinner at Ali...
24,2012-09-03,nvhdKKdvBNw7XeH5OQ4oMQ,XVvbDeYn5Dk-MteNHwjC7Q,pbEiXam9YJL3neCYHGwLUA,N,2,0,0,4,I agree with many of the yelpers from 3 to fiv...
25,2012-08-28,GJsvC0riezPv,R318sTI6PPW_9NVCo5kVug,pbEiXam9YJL3neCYHGwLUA,N,1,0,1,5,what can be said that hasn't already been said...
26,2012-08-04,MzJApoBUAVAu2LdQJ6VaBQ,wHR7qjlJsXs3S7VaxxwI3Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,An experience to remember!!! We had a 15 cours...
27,2012-07-13,drAqZGZcUbZY4wQE8w8mXA,9eDVC1mdI0RRt5y77PwylQ,pbEiXam9YJL3neCYHGwLUA,N,0,3,2,5,I flew out from Los Angeles just to have dinne...
28,2012-08-08,obzt0gcx3n,FzemMECB9UV6UAPqg3P88Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,"Amazing, excellent molecular gastronomy at it'..."
29,2012-08-27,3IYippxq4tQJ7SBmERF1Og,a-yKADt-y4lahw3jwu3rjA,pbEiXam9YJL3neCYHGwLUA,N,0,0,4,3,The service deserves five stars. The food is o...
...,...,...,...,...,...,...,...,...,...,...
61511,2012-08-04,Qt88,csvvb8ysqAP-xwac7_bq1g,ksccA8XUDV6b2h-PmuZKPg,N,0,0,2,1,Went to the grand opening party and sent the l...
61512,2012-08-07,42WYMrUYX4hgZOrjaw,zEd0T3-wXfFWOMkypYC8Mw,ksccA8XUDV6b2h-PmuZKPg,N,0,0,0,5,"Great Grand Opening party, hope you do it ever..."
61513,2012-05-27,qInFCOR0W4xf,9OHb0MKXwB-_B0ZIV9hRPQ,ksccA8XUDV6b2h-PmuZKPg,N,0,0,1,4,I was here for the opening party and they defi...
61514,2012-05-25,yexJYbfhWhwup,Xmr6fmVI-KYMKYDRm3PMfQ,ksccA8XUDV6b2h-PmuZKPg,N,0,0,1,5,"RevBrew grand opening! Bands, Food Trucks, & B..."
61515,2012-06-04,gDJAZ9rR8DSAlnEC,_Trm6mqf-ueAU0sHouKKtA,ksccA8XUDV6b2h-PmuZKPg,N,0,0,0,4,"Grand Opening party was pretty rad. 35,000 squ..."
61516,2009-04-05,VflhKYC,QyjJ6WFZLBzgXopffaVCNw,WSdmu6o6H4udkjbs6K5n5w,N,0,2,2,5,"Authentic Italian deli, formerly of the more w..."
61517,2011-09-05,t7L9OJf,naRLMs7Y4w5ZWj4bdUMmeQ,WSdmu6o6H4udkjbs6K5n5w,N,0,0,0,1,I the pizza. I wish I hadn't.
61518,2009-04-20,xo0XbpW2boGa,P1oK3UGg1UjzwjvKh0qNqQ,0Cc0SBLU0joTqsnbitQ7Ng,N,6,6,8,5,Yes it IS a miracle! I want more chilaquiles!!...
61519,2009-02-07,hwvlKugaq8z2xV0,2fD5eklHrWWbmYtGiZtbsw,0Cc0SBLU0joTqsnbitQ7Ng,N,1,3,3,5,If you haven't been here then go. As a residen...
61520,2011-01-10,QqAYMS3VT1tVUuR4G,2kKg1o30DLsSrgmxHVZk-g,0Cc0SBLU0joTqsnbitQ7Ng,N,0,0,0,5,One of the best carne asada tacos I've ever ha...
61521,2011-12-19,5ZExEJypi25pUfA-k,nMMbo120LzRgU2deWdR9AQ,0Cc0SBLU0joTqsnbitQ7Ng,N,0,0,0,5,man this place is so good it doesn't even matt...
61522,2009-08-04,xrDSjkmJou8q6,an45f8z9YPJc8GTvkcGMQw,0Cc0SBLU0joTqsnbitQ7Ng,N,3,1,1,5,OK. Get ready for a totally biased review. I g...
61523,2009-10-08,6UsJohoalj3RSSr,RsnwMzpPTgEnpiG8KMU-ng,0Cc0SBLU0joTqsnbitQ7Ng,N,0,1,1,5,quite possibly my favorite mexican food chicag...
61524,2009-07-28,M8R8oEi13L7wB,-8fCkXTfKWFalj8jUhFryQ,lOLS1M0WmBlR7DV1J34lfA,N,2,2,3,5,I have to give this place a 5 star because the...
61525,2008-02-28,A8of91bcC9DR,6KLAeasSyvwM-k57VWYF0Q,lOLS1M0WmBlR7DV1J34lfA,N,0,2,3,4,"Lately, everything I've tried on the menu is q..."
61526,2009-09-03,9ufJ5bTpPlxSA,-3r0CX7niGCyUnqkKZcmSQ,lOLS1M0WmBlR7DV1J34lfA,N,1,0,0,5,The problem I face is that every time certain ...
61527,2009-02-06,7dEFrbfx8iQuDbL,Ai6hdmV5-nVglscxLbxSGw,lOLS1M0WmBlR7DV1J34lfA,N,0,1,1,4,i like san luis because of their speciality: a...
61528,2007-08-29,ZYT,NyltIuiXtKMuqtVH85uyxQ,6XVXM78gBuU3gpq2hTOgJA,N,4,4,4,3,"Hmmmm, OK. There isn't too much in White Sox L..."
61529,2007-05-05,Z0AP6PXiFIvmG7,zG8PJLc4YHWxhcqUf6lyBg,6XVXM78gBuU3gpq2hTOgJA,N,2,0,0,5,"I came here at 3 PM once, before a 7 PM start,..."
61530,2011-11-18,FefmFaWa,vX6aOMQ3HWCbwZVfCkCauw,6XVXM78gBuU3gpq2hTOgJA,N,0,0,0,3,We were surprised to have been eagerly roped i...
61531,2008-01-11,efXJVadH,2SP9ZHlyZe3oyXpObBQIvQ,6XVXM78gBuU3gpq2hTOgJA,N,0,0,1,5,I went to a party at this bar & grill yesterda...
61532,2011-08-04,lTaW3Zb3E,W5-Z3HE7quOxia9R9kQQIQ,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,4,I love me some Cafezazzo! I come here a few ti...
61533,2010-07-30,xM9,lZgGf83NCctO5mkGWXcAlQ,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,4,So after all these years I decided to check ou...
61534,2008-10-29,#NAME?,CtHKKxsRoWl-9KuYPoG3RA,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,5,I truly love this place! Just like everyone st...
61535,2011-10-08,BOxgSHru1VycS,kHIFPG3NLehDo-6uRUjWYA,_KI0Y2UO68kJuTFUKucaXQ,N,0,0,1,5,If you want seafood this is place to go. It is...
61536,2012-04-07,I6pazvTPUqRtU,fUXNHG4x1AN9oPpBSpCtUw,_KI0Y2UO68kJuTFUKucaXQ,N,1,0,0,5,I've passed this place a bunch of times on my ...
61537,2009-06-05,gu7FbL,QQCm2oqSnnz24Z-yHeMtxQ,_KI0Y2UO68kJuTFUKucaXQ,N,0,1,1,4,Rubino's is not really setup as a retail opera...
61538,2012-05-06,hLwn6zw,OXRKydSyzC35n2fNUnbopg,XvP-kanjF6SpchosRk0N5g,N,0,0,0,5,This place is amazing. The food is great and y...
61539,2011-01-08,KEkOzeO9YJ,NE8ULc362aFvnkTDgvZbcA,XvP-kanjF6SpchosRk0N5g,N,0,1,2,2,OK went back the next day as I was driving by ...
61540,2010-01-25,xYkvLLWMyyYO3JEX68H,VaPi2-eXcgIpRF_LGSJ_cA,XvP-kanjF6SpchosRk0N5g,N,0,0,0,5,"Delicious, rather authentic Mexican food, must..."

In [49]:
full_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61541 entries, 0 to 61540
Data columns (total 10 columns):
date           61541 non-null datetime64[ns]
review_id      61541 non-null object
reviewer_id    61541 non-null object
business_id    61541 non-null object
label          61541 non-null object
usefull        61541 non-null int64
funny          61541 non-null int64
cool           61541 non-null int64
Stars          61541 non-null int64
review         61541 non-null object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 4.7+ MB

In [50]:
full_review.describe()

            usefull         funny          cool         Stars
count  61541.000000  61541.000000  61541.000000  61541.000000
mean       0.453584      0.529468      0.819031      3.976633
std        1.628040      1.671220      1.897604      1.109216
min        0.000000      0.000000      0.000000      1.000000
25%        0.000000      0.000000      0.000000      4.000000
50%        0.000000      0.000000      0.000000      4.000000
75%        0.000000      1.000000      1.000000      5.000000
max       78.000000    170.000000     84.000000      5.000000

In [52]:
def text_process(review):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in review if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # remove any stopwords
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [55]:
p_reviews=full_review['review'].apply(text_process)

In [57]:
len_reviews=[len(rev) for rev in p_reviews]

In [58]:
full_review['p_reviews']=p_reviews
full_review['len_reviews']=len_reviews

In [61]:
full_review['extreme_rating']=full_review['Stars'].apply(lambda x: 1 if x==1 or x==5 else 0)

In [82]:
review_count=full_review.groupby('business_id',sort=False).count()['Stars']
review_mean=full_review.groupby('business_id',sort=False).mean()['Stars']
mean_rating=[]
for i in range(review_mean.shape[0]):
    mean_rating.extend([review_mean[i]] * review_count[i])
full_review['mean_rating']=mean_rating

In [147]:
full_review['rating_deviation']=np.abs(full_review['Stars']-full_review['mean_rating'])/4

In [108]:
temp=full_review.groupby(['reviewer_id','date'],).count()['review_id']
temp_index=temp.index

In [135]:
maxrevs=[]
reviewers=[temp_index[0][0]]
temp2=[temp[0]]
for i in range(1,len(temp)):
    if(temp_index[i][0]==temp_index[i-1][0]):
        temp2.append(temp[i])
    else:
        maxrevs.append(np.max(temp2))
        reviewers.append(temp_index[i][0])
        temp2=[temp[i]]
maxrevs.append(np.max(temp2))

In [136]:
maxrev=full_review.groupby(['reviewer_id','date']).count()['review_id'].max()

In [137]:
maxrevs=np.array(maxrevs/maxrev)

In [142]:
MNR=[]
for i in range(full_review.shape[0]):
    ind=reviewers.index(full_review.reviewer_id[i])
    MNR.append(maxrevs[ind])

In [146]:
full_review['MNR']=MNR

In [167]:
unique_revs=full_review['reviewer_id'].unique()

In [168]:
extreme_ratio=[]
for i in range(len(unique_revs)):
    if(i%100==0):
        print(i)
    df=full_review[full_review['reviewer_id']==unique_revs[i]]
    t_count=df.shape[0]
    ex_count=np.sum(df['extreme_rating'])
    extreme_ratio.append(ex_count/t_count)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500

In [169]:
ex_ratio=[]
for i in range(full_review.shape[0]):
    ind=list(unique_revs).index(full_review.reviewer_id[i])
    ex_ratio.append(extreme_ratio[ind])

In [170]:
full_review['extreme_ratio']=ex_ratio

In [173]:
vect = TfidfVectorizer(min_df=1)

In [184]:
cosin=[]
for i in range(len(unique_revs)):
    if(i%100==0):
        print(i)
    df=full_review[full_review['reviewer_id']==unique_revs[i]]
    revs=df['p_reviews'].apply(lambda x: ' '.join(x))
    max_value=0
    if(revs.values[0]!=''):
        tfidf = vect.fit_transform(revs)
        cosin_mat=(tfidf * tfidf.T).A
        np.fill_diagonal(cosin_mat, -np.inf)
        max_value = cosin_mat.max()
    cosin.append(max_value)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500

In [185]:
MCS=[]
for i in range(full_review.shape[0]):
    ind=list(unique_revs).index(full_review.reviewer_id[i])
    MCS.append(cosin[ind])

In [186]:
full_review['MCS']=MCS

In [187]:
full_review

,date,review_id,reviewer_id,business_id,label,usefull,funny,cool,Stars,review,p_reviews,len_reviews,extreme_rating,rating_deviation,mean_rating,MNR,extreme_ratio,MCS
0,2012-09-22,GtwU21YOQn-wf4vWRUIx6w,bNYesZ944s6IJVowOnB0iA,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,"Unlike Next, which we'd eaten at the previous ...","[Unlike, Next, wed, eaten, previous, night, di...",450,1,0.099206,4.603175,0.055556,0.500000,0.107020
1,2012-09-22,0LpVTc3,TRKxLC3y-ZvP45e5iilMtw,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,Probably one of the best meals I've had ever. ...,"[Probably, one, best, meals, Ive, ever, perfor...",34,1,0.099206,4.603175,0.055556,1.000000,-inf
2,2012-09-19,tljtLzf68Fkwf,0EMm8umAqXZzyhxNpL4M9g,pbEiXam9YJL3neCYHGwLUA,N,0,0,2,3,Service was impeccable. Experience and present...,"[Service, impeccable, Experience, presentation...",25,0,0.400794,4.603175,0.055556,0.000000,-inf
3,2012-09-06,iSN,DlwexC7z88ymAzu45skODw,pbEiXam9YJL3neCYHGwLUA,N,3,0,8,3,"The problem with places like this, given the e...","[problem, places, like, given, exhorbitant, co...",206,0,0.400794,4.603175,0.055556,0.000000,-inf
4,2012-09-09,Jmwrh7,kW2dk1CWihmh3g7k9N2G8A,pbEiXam9YJL3neCYHGwLUA,N,0,2,1,5,I have no idea how to write my review - dining...,"[idea, write, review, dining, Alinea, brings, ...",82,1,0.099206,4.603175,0.055556,0.363636,0.201236
5,2012-08-30,lKlceLWoePzeuvFD3sj4mw,HxXEcMDDTJFUqVfhPF9M8Q,pbEiXam9YJL3neCYHGwLUA,N,1,1,3,5,Despite the first-world tragedy I endured in a...,"[Despite, firstworld, tragedy, endured, effort...",197,1,0.099206,4.603175,0.055556,1.000000,-inf
6,2012-09-08,PBS2uyee9V5IpFfTropxbw,OW2H-GkKnlVEBPuGHIaiFg,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,5,"Overall, was it worth the hype? Yes and more. ...","[Overall, worth, hype, Yes, worth, every, penn...",236,1,0.099206,4.603175,0.055556,1.000000,-inf
7,2012-08-24,PkwbB,BSh3h1J4mdSmEsb8FFdf0Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,8,3,There are already TONS of professional & amate...,"[already, TONS, professional, amateur, reviews...",230,0,0.400794,4.603175,0.111111,0.250000,0.150627
8,2012-08-22,MRdliMXsmP1ViLjA5oCO,F3mbveXX30Ou0gpDY6IrCQ,pbEiXam9YJL3neCYHGwLUA,N,3,7,3,5,Your life is a countdown ever since you're bor...,"[life, countdown, ever, since, youre, born, li...",265,1,0.099206,4.603175,0.111111,0.538462,0.235199
9,2012-08-23,z-j4X,NvSnBp4fTpNOfDwm2GWusA,pbEiXam9YJL3neCYHGwLUA,N,0,0,3,5,Lots of complaints about how difficult it is t...,"[Lots, complaints, difficult, get, get, hard, ...",70,1,0.099206,4.603175,0.055556,1.000000,-inf
10,2012-08-26,VXtDGw7E0guWdXLOtzKJ3w,dCbC5DeMbsRsP0bw7RRG0w,pbEiXam9YJL3neCYHGwLUA,N,0,0,4,3,1st I will say I'm not a foodie but I enjoy di...,"[1st, say, Im, foodie, enjoy, dining, w, foodi...",112,0,0.400794,4.603175,0.055556,0.000000,-inf
11,2012-09-11,V0PU0ciEBeNiHHS1,-3Mzc2O6jmYLWQJcIJdvAA,pbEiXam9YJL3neCYHGwLUA,N,0,1,1,5,Today marks one year since my dinner at Alinea...,"[Today, marks, one, year, since, dinner, Aline...",65,1,0.099206,4.603175,0.055556,0.333333,0.060689
12,2012-08-16,revID_update_res1,Or40sZeUkVa2w1SCjhaUVg,pbEiXam9YJL3neCYHGwLUA,N,0,1,3,5,"In my four years as a member of Yelp!, I've wr...","[four, years, member, Yelp, Ive, written, gran...",344,1,0.099206,4.603175,0.055556,1.000000,-inf
13,2012-08-04,9Q17H2GMBFeRMOS1Ni-I2Q,tToOHav143V1NXH0nf_YIA,pbEiXam9YJL3neCYHGwLUA,N,10,10,10,5,"I had wanted to visit Alinea since 2007, but w...","[wanted, visit, Alinea, since, 2007, never, or...",225,1,0.099206,4.603175,0.111111,0.428571,0.182486
14,2012-09-15,Hk9BR0a,EkItn2a_Fx1KE9Q5amo7JA,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,I dined at Alinea a few weeks ago with my son ...,"[dined, Alinea, weeks, ago, son, 25th, birthda...",218,1,0.099206,4.603175,0.055556,1.000000,0.088289
15,2012-08-21,MgarFT5mQE6Gq1eNAfw4Fw,0SvPdzpIEHQFJOvnPt9zxQ,pbEiXam9YJL3neCYHGwLUA,N,1,1,0,5,"So, we were fortunate enough to score Sunday d...","[fortunate, enough, score, Sunday, dinner, res...",188,1,0.099206,4.603175,0.055556,1.000000,-inf
16,2012-08-06,8cP116ZiSEmSv8vYTI6RIA,hFaZatmXXpiEDyMFaLejmw,pbEiXam9YJL3neCYHGwLUA,N,2,3,1,5,All of these reviews likely tell you the vario...,"[reviews, likely, tell, various, ways, courses...",113,1,0.099206,4.603175,0.111111,0.625000,0.068249
17,2012-08-23,UgYDx0tIBklPYQM1VS-B,NAWMYBSkEPAEYp9YT7vM_Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,This is really the greatest restaurant I have ...,"[really, greatest, restaurant, forever, truly,...",76,1,0.099206,4.603175,0.055556,1.000000,-inf
18,2012-08-13,6A7MFnTHM45U0pKl379KRw,_Es4as5v1edu5WxeMvWHEg,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,4,Maybe I should have read reviews of this place...,"[Maybe, read, reviews, place, went, bit, exper...",116,0,0.150794,4.603175,0.055556,0.000000,-inf
19,2012-08-08,If-jhodOvle7Qm6LBK-GTA,yGrCzVPdeHTiFl5KfUVZBA,pbEiXam9YJL3neCYHGwLUA,N,0,1,1,5,I have never worked this hard to get a reserva...,"[never, worked, hard, get, reservation, Lookin...",147,1,0.099206,4.603175,0.055556,1.000000,-inf
20,2012-09-08,Xz9kC-QlnKL1CO6hSihR0w,7MczEWaY3Ic6p4kBkKH0gw,pbEiXam9YJL3neCYHGwLUA,N,0,0,1,5,"The best restaurant I have ever been to, hands...","[best, restaurant, ever, hands, Well, even, Fr...",8,1,0.099206,4.603175,0.166667,0.333333,0.112647
21,2012-08-30,JJB4ji7KzToqwdW3CRad,TYfZrIzz08VGmvvvGZhqyw,pbEiXam9YJL3neCYHGwLUA,N,0,0,5,5,"First, let me start by saying that it took me ...","[First, let, start, saying, took, two, years, ...",181,1,0.099206,4.603175,0.055556,0.500000,0.120359
22,2012-08-16,aeEjv1lz5q0E0k6uf0gZ4w,gmluXHnW8aihzYow1zVoRQ,pbEiXam9YJL3neCYHGwLUA,N,0,0,3,2,Part of me wants to give this resto five stars...,"[Part, wants, give, resto, five, stars, part, ...",70,0,0.650794,4.603175,0.055556,0.000000,-inf
23,2012-08-12,6--qR6eWCaLsVFsoZYELAA,9_Hqx7Bf5vwQsgP2g-WCCQ,pbEiXam9YJL3neCYHGwLUA,N,1,1,1,5,The day had finally come for our dinner at Ali...,"[day, finally, come, dinner, Alinea, never, tr...",96,1,0.099206,4.603175,0.055556,1.000000,-inf
24,2012-09-03,nvhdKKdvBNw7XeH5OQ4oMQ,XVvbDeYn5Dk-MteNHwjC7Q,pbEiXam9YJL3neCYHGwLUA,N,2,0,0,4,I agree with many of the yelpers from 3 to fiv...,"[agree, many, yelpers, 3, five, star, posting,...",62,0,0.150794,4.603175,0.111111,0.000000,0.074285
25,2012-08-28,GJsvC0riezPv,R318sTI6PPW_9NVCo5kVug,pbEiXam9YJL3neCYHGwLUA,N,1,0,1,5,what can be said that hasn't already been said...,"[said, hasnt, already, said, dinner, past, sun...",108,1,0.099206,4.603175,0.111111,0.500000,0.036725
26,2012-08-04,MzJApoBUAVAu2LdQJ6VaBQ,wHR7qjlJsXs3S7VaxxwI3Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,An experience to remember!!! We had a 15 cours...,"[experience, remember, 15, course, meal, wine,...",49,1,0.099206,4.603175,0.111111,0.500000,0.031201
27,2012-07-13,drAqZGZcUbZY4wQE8w8mXA,9eDVC1mdI0RRt5y77PwylQ,pbEiXam9YJL3neCYHGwLUA,N,0,3,2,5,I flew out from Los Angeles just to have dinne...,"[flew, Los, Angeles, dinner, Alinea, Although,...",322,1,0.099206,4.603175,0.055556,1.000000,0.120341
28,2012-08-08,obzt0gcx3n,FzemMECB9UV6UAPqg3P88Q,pbEiXam9YJL3neCYHGwLUA,N,0,0,0,5,"Amazing, excellent molecular gastronomy at it'...","[Amazing, excellent, molecular, gastronomy, be...",34,1,0.099206,4.603175,0.055556,1.000000,-inf
29,2012-08-27,3IYippxq4tQJ7SBmERF1Og,a-yKADt-y4lahw3jwu3rjA,pbEiXam9YJL3neCYHGwLUA,N,0,0,4,3,The service deserves five stars. The food is o...,"[service, deserves, five, stars, food, overhyp...",27,0,0.400794,4.603175,0.055556,0.000000,-inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61511,2012-08-04,Qt88,csvvb8ysqAP-xwac7_bq1g,ksccA8XUDV6b2h-PmuZKPg,N,0,0,2,1,Went to the grand opening party and sent the l...,"[Went, grand, opening, party, sent, letter, fo...",157,1,0.700000,3.800000,0.055556,1.000000,-inf
61512,2012-08-07,42WYMrUYX4hgZOrjaw,zEd0T3-wXfFWOMkypYC8Mw,ksccA8XUDV6b2h-PmuZKPg,N,0,0,0,5,"Great Grand Opening party, hope you do it ever...","[Great, Grand, Opening, party, hope, every, year]",7,1,0.300000,3.800000,0.055556,1.000000,-inf
61513,2012-05-27,qInFCOR0W4xf,9OHb0MKXwB-_B0ZIV9hRPQ,ksccA8XUDV6b2h-PmuZKPg,N,0,0,1,4,I was here for the opening party and they defi...,"[opening, party, definitely, great, job, picki...",45,0,0.050000,3.800000,0.055556,0.400000,0.123915
61514,2012-05-25,yexJYbfhWhwup,Xmr6fmVI-KYMKYDRm3PMfQ,ksccA8XUDV6b2h-PmuZKPg,N,0,0,1,5,"RevBrew grand opening! Bands, Food Trucks, & B...","[RevBrew, grand, opening, Bands, Food, Trucks,...",8,1,0.300000,3.800000,0.055556,1.000000,-inf
61515,2012-06-04,gDJAZ9rR8DSAlnEC,_Trm6mqf-ueAU0sHouKKtA,ksccA8XUDV6b2h-PmuZKPg,N,0,0,0,4,"Grand Opening party was pretty rad. 35,000 squ...","[Grand, Opening, party, pretty, rad, 35000, sq...",23,0,0.050000,3.800000,0.111111,0.461538,0.179853
61516,2009-04-05,VflhKYC,QyjJ6WFZLBzgXopffaVCNw,WSdmu6o6H4udkjbs6K5n5w,N,0,2,2,5,"Authentic Italian deli, formerly of the more w...","[Authentic, Italian, deli, formerly, working, ...",106,1,0.500000,3.000000,0.055556,0.400000,0.133419
61517,2011-09-05,t7L9OJf,naRLMs7Y4w5ZWj4bdUMmeQ,WSdmu6o6H4udkjbs6K5n5w,N,0,0,0,1,I the pizza. I wish I hadn't.,"[pizza, wish, hadnt]",3,1,0.500000,3.000000,0.055556,1.000000,-inf
61518,2009-04-20,xo0XbpW2boGa,P1oK3UGg1UjzwjvKh0qNqQ,0Cc0SBLU0joTqsnbitQ7Ng,N,6,6,8,5,Yes it IS a miracle! I want more chilaquiles!!...,"[Yes, miracle, want, chilaquiles, went, pick, ...",50,1,0.000000,5.000000,0.055556,0.571429,0.091525
61519,2009-02-07,hwvlKugaq8z2xV0,2fD5eklHrWWbmYtGiZtbsw,0Cc0SBLU0joTqsnbitQ7Ng,N,1,3,3,5,If you haven't been here then go. As a residen...,"[havent, go, resident, Pilsen, 10, years, best...",21,1,0.000000,5.000000,0.111111,1.000000,0.028846
61520,2011-01-10,QqAYMS3VT1tVUuR4G,2kKg1o30DLsSrgmxHVZk-g,0Cc0SBLU0joTqsnbitQ7Ng,N,0,0,0,5,One of the best carne asada tacos I've ever ha...,"[One, best, carne, asada, tacos, Ive, ever, ta...",58,1,0.000000,5.000000,0.055556,0.250000,0.097080
61521,2011-12-19,5ZExEJypi25pUfA-k,nMMbo120LzRgU2deWdR9AQ,0Cc0SBLU0joTqsnbitQ7Ng,N,0,0,0,5,man this place is so good it doesn't even matt...,"[man, place, good, doesnt, even, matter, dont,...",9,1,0.000000,5.000000,0.055556,1.000000,-inf
61522,2009-08-04,xrDSjkmJou8q6,an45f8z9YPJc8GTvkcGMQw,0Cc0SBLU0joTqsnbitQ7Ng,N,3,1,1,5,OK. Get ready for a totally biased review. I g...,"[OK, Get, ready, totally, biased, review, give...",119,1,0.000000,5.000000,0.055556,1.000000,0.051201
61523,2009-10-08,6UsJohoalj3RSSr,RsnwMzpPTgEnpiG8KMU-ng,0Cc0SBLU0joTqsnbitQ7Ng,N,0,1,1,5,quite possibly my favorite mexican food chicag...,"[quite, possibly, favorite, mexican, food, chi...",32,1,0.000000,5.000000,0.055556,0.333333,0.062280
61524,2009-07-28,M8R8oEi13L7wB,-8fCkXTfKWFalj8jUhFryQ,lOLS1M0WmBlR7DV1J34lfA,N,2,2,3,5,I have to give this place a 5 star because the...,"[give, place, 5, star, damn, good, food, damn,...",183,1,0.125000,4.500000,0.055556,0.600000,0.195300
61525,2008-02-28,A8of91bcC9DR,6KLAeasSyvwM-k57VWYF0Q,lOLS1M0WmBlR7DV1J34lfA,N,0,2,3,4,"Lately, everything I've tried on the menu is q...","[Lately, everything, Ive, tried, menu, quite, ...",80,0,0.125000,4.500000,0.055556,0.500000,0.080679
61526,2009-09-03,9ufJ5bTpPlxSA,-3r0CX7niGCyUnqkKZcmSQ,lOLS1M0WmBlR7DV1J34lfA,N,1,0,0,5,The problem I face is that every time certain ...,"[problem, face, every, time, certain, friends,...",63,1,0.125000,4.500000,0.055556,0.600000,0.072350
61527,2009-02-06,7dEFrbfx8iQuDbL,Ai6hdmV5-nVglscxLbxSGw,lOLS1M0WmBlR7DV1J34lfA,N,0,1,1,4,i like san luis because of their speciality: a...,"[like, san, luis, speciality, alambres, kind, ...",38,0,0.125000,4.500000,0.111111,0.750000,0.031253
61528,2007-08-29,ZYT,NyltIuiXtKMuqtVH85uyxQ,6XVXM78gBuU3gpq2hTOgJA,N,4,4,4,3,"Hmmmm, OK. There isn't too much in White Sox L...","[Hmmmm, OK, isnt, much, White, Sox, Land, Cobb...",103,0,0.250000,4.000000,0.055556,0.000000,0.100334
61529,2007-05-05,Z0AP6PXiFIvmG7,zG8PJLc4YHWxhcqUf6lyBg,6XVXM78gBuU3gpq2hTOgJA,N,2,0,0,5,"I came here at 3 PM once, before a 7 PM start,...","[came, 3, PM, 7, PM, start, drink, alone, stud...",20,1,0.250000,4.000000,0.055556,0.250000,0.046717
61530,2011-11-18,FefmFaWa,vX6aOMQ3HWCbwZVfCkCauw,6XVXM78gBuU3gpq2hTOgJA,N,0,0,0,3,We were surprised to have been eagerly roped i...,"[surprised, eagerly, roped, pop, trivia, game,...",37,0,0.250000,4.000000,0.055556,0.000000,0.046323
61531,2008-01-11,efXJVadH,2SP9ZHlyZe3oyXpObBQIvQ,6XVXM78gBuU3gpq2hTOgJA,N,0,0,1,5,I went to a party at this bar & grill yesterda...,"[went, party, bar, grill, yesterday, pleasant,...",59,1,0.250000,4.000000,0.055556,1.000000,-inf
61532,2011-08-04,lTaW3Zb3E,W5-Z3HE7quOxia9R9kQQIQ,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,4,I love me some Cafezazzo! I come here a few ti...,"[love, Cafezazzo, come, times, around, year, k...",52,0,0.083333,4.333333,0.055556,0.000000,-inf
61533,2010-07-30,xM9,lZgGf83NCctO5mkGWXcAlQ,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,4,So after all these years I decided to check ou...,"[years, decided, check, Cafezazzo, neighborhoo...",71,0,0.083333,4.333333,0.055556,0.000000,0.165170
61534,2008-10-29,#NAME?,CtHKKxsRoWl-9KuYPoG3RA,fHJRHfeLQl-MxUSdUkI9rg,N,0,0,0,5,I truly love this place! Just like everyone st...,"[truly, love, place, like, everyone, states, r...",67,1,0.166667,4.333333,0.111111,0.666667,0.144941
61535,2011-10-08,BOxgSHru1VycS,kHIFPG3NLehDo-6uRUjWYA,_KI0Y2UO68kJuTFUKucaXQ,N,0,0,1,5,If you want seafood this is place to go. It is...,"[want, seafood, place, go, warehouse, man, hel...",22,1,0.083333,4.666667,0.055556,1.000000,-inf
61536,2012-04-07,I6pazvTPUqRtU,fUXNHG4x1AN9oPpBSpCtUw,_KI0Y2UO68kJuTFUKucaXQ,N,1,0,0,5,I've passed this place a bunch of times on my ...,"[Ive, passed, place, bunch, times, way, Olympi...",42,1,0.083333,4.666667,0.055556,0.666667,0.087889
61537,2009-06-05,gu7FbL,QQCm2oqSnnz24Z-yHeMtxQ,_KI0Y2UO68kJuTFUKucaXQ,N,0,1,1,4,Rubino's is not really setup as a retail opera...,"[Rubinos, really, setup, retail, operation, pr...",26,0,0.166667,4.666667,0.055556,0.000000,-inf
61538,2012-05-06,hLwn6zw,OXRKydSyzC35n2fNUnbopg,XvP-kanjF6SpchosRk0N5g,N,0,0,0,5,This place is amazing. The food is great and y...,"[place, amazing, food, great, cannot, beat, pr...",17,1,0.250000,4.000000,0.055556,1.000000,-inf
61539,2011-01-08,KEkOzeO9YJ,NE8ULc362aFvnkTDgvZbcA,XvP-kanjF6SpchosRk0N5g,N,0,1,2,2,OK went back the next day as I was driving by ...,"[OK, went, back, next, day, driving, lunchtime...",62,0,0.500000,4.000000,0.055556,0.000000,0.075806
61540,2010-01-25,xYkvLLWMyyYO3JEX68H,VaPi2-eXcgIpRF_LGSJ_cA,XvP-kanjF6SpchosRk0N5g,N,0,0,0,5,"Delicious, rather authentic Mexican food, must...","[Delicious, rather, authentic, Mexican, food, ...",25,1,0.250000,4.000000,0.055556,1.000000,-inf

In [189]:
full_review.to_csv('Extracted_features.csv')

In [188]:
print(full_review.groupby('label').describe())

           MCS                                                  MNR            \
         count mean std  min  25%       50%       75%  max    count      mean
label
N      53400.0 -inf NaN -inf -inf  0.074927  0.143081  1.0  53400.0  0.082222
Y       8141.0 -inf NaN -inf  NaN       NaN  0.000000  1.0   8141.0  0.069607

       ...  rating_deviation            usefull                               \
       ...               75%       max    count      mean      std  min  25%
label  ...
N      ...          0.270130  0.900794  53400.0  0.522734  1.73737  0.0  0.0
Y      ...          0.384558  0.746959   8141.0  0.000000  0.00000  0.0  0.0


       50%  75%   max
label
N      0.0  0.0  78.0
Y      0.0  0.0   0.0

[2 rows x 88 columns]

/Users/anvitmangal/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4406: RuntimeWarning: invalid value encountered in multiply
  x2 = take(ap, indices_above, axis=axis) * weights_above